# Generated by Django 4.0 on 2021-12-20 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadística',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Total_personas', models.IntegerField()),
                ('Total_solicitudes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'estadística',
                'verbose_name_plural': 'estadísticas',
                'db_table': 'Estadística',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=30, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('avatar', models.ImageField(upload_to='images/products/main')),
                ('fecha_de_creacion', models.DateField(default=datetime.datetime.now)),
                ('fecha_de_actualizacion', models.DateField(default=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
                'ordering': ['id'],
            },
        ),
    ]
