# Generated by Django 4.0 on 2021-12-20 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_persona_cantidad_de_solicitudes_alter_persona_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadística',
            options={'ordering': ['id'], 'verbose_name': 'Estadística', 'verbose_name_plural': 'estadísticas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(upload_to='Personas%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_de_actualizacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
